spring.application.name=auth-service
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/auth-service
spring.datasource.username=
spring.datasource.password=

spring.cache.type=redis
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=
spring.mail.password=
spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


api.security.token=${JWT_SECRET:my-secret-key}
server.port=8082
