spring.application.name=bankingPlatform
spring.datasource.url=jdbc:postgresql://localhost:5432/bankingPlatform
spring.datasource.username=postgres
spring.datasource.password=postgres

api.security.token=${JWT_SECRET:my-secret-key}
